selection and cursor pos
Insality/druid pull request #258
Opened 2024-02-26 11:58 UTC by Sublustris

Need some help in  rich_input.lua   -  line 186

2024-03-13 08:17 UTC, Sublustris commented
That's all the features we want to add this time,  please let us know when you would be ready with code review. If something needs fixes, let us know too pls.

2024-03-18 22:31 UTC, Insality requested changes
Thanks for the changes!

Let's first fix all UX things, like more accurate selection and input handling (currently the rich input consumes all the input)

2024-03-18 22:31 UTC, Insality commented on druid/extended/input.lua
> +-- @tfield[opt=false] bool SKIP_INPUT_KEYS If true, input component will skip processing keys input allowing to process it completely in other components
I think we should escape the changing input process order from the components

2024-03-18 22:31 UTC, Insality commented on druid/custom/rich_input/rich_input.lua
> +	if self.touch_pos_x then
Seems like the touch_pos_x should be as arg of function, wdyt?

2024-03-18 22:31 UTC, Insality commented on druid/custom/rich_input/rich_input.lua
> +	self.input.cursor_letter_index = 0
Already inited in input component

2024-03-18 22:31 UTC, Insality commented on druid/custom/rich_input/rich_input.lua
> +			cursor_delta =  gap + self.text:get_text_size(string.sub(text, 1, i)) - self.half_cursor_width
Looks like half_cursor_width can be removed, I rely on this video

https://github.com/Insality/druid/assets/3294627/cbb06ee0-78cd-41ba-9de5-3c1dc71ea97a

2024-03-18 22:31 UTC, Insality commented on druid/custom/rich_input/rich_input.lua
> +	self.input.style.NO_CONSUME_INPUT_WHILE_SELECTED = true
I think the rich input should not change these style settings (and for skip input keys same)

2024-03-18 22:31 UTC, Insality commented on druid/custom/rich_input/rich_input.lua
> +		gui.set_position(self.cursor, vmath.vector3(0, 0, 0))
You can create a `local TEMP_VECTOR = vector3(0)` in module scope, change their fields instead creating vector each time. It allows to save a bit of memory

2024-03-18 22:31 UTC, Insality commented on druid/custom/rich_input/rich_input.lua
> +	self.action_pos_x = action.screen_x
The values `action_pos_x` and `touch_pos_x` should not be stored in rich input component. You can use it as a local variables inside only on_input functions

2024-03-18 22:31 UTC, Insality commented on druid/custom/rich_input/rich_input.lua
> +			--self.input.cursor_letter_index = self.input.cursor_letter_index +1
Empty if + comments

2024-03-18 22:31 UTC, Insality commented on druid/extended/input.lua
> +			--return true
Looks like a mistake

2024-08-27 14:06 UTC, closed without merging